name: Build

on:
  push:
    branches:
      - main  # También puedes agregar otras ramas aquí
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # No hacer un "shallow clone" para una mejor relevancia en el análisis

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener la información de PR si la hay
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
